# Gains for the Proportional-Derivative Joint Space Controller
# P and D gains for each axis.
impedance_ctrl: 
  #proportional
  gains_p: [80, 600, 600, 150, 40, 5]
  gains_p_cart: [1, 1, 1, 1, 1, 1]

  #derivative
  gains_d: [75, 75, 75, 73, 15, 5]
  gains_d_cart: [10, 10, 10, 10, 10, 10]
  #integral
  gains_i: [1,5,5,2,1,1]
  gains_i_cart: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]

  # Desired position in deg [J1, J2, J3, J4, J5, J6], e.g. [90, -45, 30, -70, 40, 40]
  # Home: [0, -90, 0, -90, 0, 0] 
  init_q: [0, -70, -110, -90, 90, 0]

  # time
  init_period: 5.0

  # adaptive controller
  learning_rate: 0.001

  # low pass filter
  low_pass_factor: 0.99

