# Gains for the Proportional-Derivative Joint Space Controller
# P and D gains for each axis.
impedance_ctrl: 
  #proportional
  gains_p: [95, 600, 600, 150, 40, 5] # try120 
  gains_p_cart: [5, 5, 5, 1, 1, 1]

  #derivative
  gains_d: [100, 200, 200, 73, 15, 5]
  gains_d_cart: [26, 26, 26, 26, 26, 26]
  #integral
  gains_i: [1,10,10,5,1,1]
  gains_i_cart: [1.3, 1.3, 1.3, 1.3, 1.3, 1.3]
  # Desired position in deg [J1, J2, J3, J4, J5, J6], e.g. [90, -45, 30, -70, 40, 40]
  # Home: [0, -90, 0, -90, 0, 0] 
  init_q: [0, -70, -110, -90, 90, 0]

  # time
  init_period: 5.0

  # adaptive controller
  learning_rate: 50

  # low pass filter
  low_pass_factor: 0.999

